### ISSUE TITLE
Relative paths should be invalid

### ISSUE THREAD

**Issue by alberto** [kaelzhang/node-ignore#20]
I think `node-ignore` should not filter relative paths starting with `./` or `../`

```
const ignore = require('ignore');
var ig = ignore().add(['.*']);
ig.filter(['foo', '.bar', './baz', '../quuz']);

Outputs: [ 'foo' ]
```

Similarly, relative ignore paths should be discarded as invalid:

```
const ignore = require('ignore')
var ig = ignore().add(['../*'])
ig.filter(['foo', '.bar', './baz', '../quuz'])
[ 'foo', '.bar', './baz' ]
```

**Comment by kaelzhang** [comment]
Let's discuss this first.

- I think relative paths like `../*` should always be ignored.
- relatvie paths like `./foo` shoule be converted to `foo` first

**Comment by alberto** [comment]
Note you can do things like `./../foo` so you are not guaranteed to always get a path in a subfolder.

That's why I think the conversion should by done by the user and `node-ignore` should not filter those, IMO.

Here is another simplified example:
```
const ignore = require('ignore')
var ig = ignore().add(['foo.js'])
ig.filter(['foo.js', 'bar.js', '../foo.js'])

[ 'bar.js' ]
```
I don't think it should filter `../foo.js`

**Comment by kaelzhang** [comment]
@alberto 

I've tried to upgrade `node-ignore` to `5.x` for `eslint`, but I found that it was harder than I expected.

There are lots of runtime logics that make `node-ignore` to filter relative paths in `eslint`, which I thought is not robust because `node-ignore` can not ensure idempotence for these cases.
----

With `ignore@5.0.2`, if we filter a relative path such as `./foo` or `../bar`, there will be an error thrown.
