### ISSUE TITLE
Feature request: .remove method

### ISSUE THREAD

**Issue by jedwards1211** [kaelzhang/node-ignore#62]
In order to use this in a watch mode tool, we need to be able to remove and replace rules whenever a `.gitignore` file is changed or even deleted.

**Comment by kaelzhang** [comment]
However, I suggest that when using `node-ignore` in a watch mode tool, **create a new ignore instance** whenever the `.gitngore` is changed.

The reason is that removing a rule and adding the the rule back is not equivalent to the original ignore rules, because the sequence of the ignore rules matters.

For example,

```.gitignore
*
*.js
!test
!test/foo.js

# Which will not ignore test/foo.js
```

If we remove `!test` then add `!test` to the end of the file

```
*
*.js
!test/foo.js
!test

# Which will ignore test/foo.js
```

So in a watch mode tool, by watching the changes of the rules then adding/removing the rules will be **error-prone**.

**Comment by jedwards1211** [comment]
That's true about the order of the rules...
I think a higher-level API for just reading in rules from files would be preferable for many cases, since it could ensure correct order and prefix rules with the subdirectory.  (not to mention loading `$GIT_DIR/info/exclude` and `core.excludesFile` when full git emulation is desired).  Guess I'll get working on it.
